export const CarActionType = {
  SET_FUEL_TYPE: 'SET_FUEL_TYPE',
  SET_SEGMENT: 'SET_SEGMENT',

  GET_CAR_LIST: 'GET_CAR_LIST',
  GET_CAR_LIST_LOADING: 'GET_CAR_LIST_LOADING',
  GET_CAR_LIST_SUCCESS: 'GET_CAR_LIST_SUCCESS',
  GET_CAR_LIST_ERROR: 'GET_CAR_LIST_ERROR',
};
